---
title: "HMM"
author: "David Barnett"
date: "January 24, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plyr)
```


```{r}
#A function that generates the data for the observed and hidden states
data_gen <- function(n, first_p, p_hidden, p_observed){
  
  first_hidden <- runif(1)
  hidden_state <- first_p > first_hidden
  hidden_data <- c(hidden_state)
  
  first_observed <- runif(1)
  observed_state <- p_observed > first_observed
  observed_data <- c(observed_state)
  
  for (i in 2:n) {
    hidden_val <- runif(1)
    if (hidden_val > p_hidden) {
      hidden_state <- !hidden_state
    }
    
    observed_val <- runif(1)
    if (observed_val < p_observed) {observed_state <- hidden_state}
    else {observed_state <- !hidden_state}
    
    hidden_data <- append(hidden_data, hidden_state)
    observed_data <- append(observed_data, observed_state)
  }
  return (list(hidden_data, observed_data))
}


```

```{r}
results <- data_gen(500,0.5,0.65,0.85)

heads_tails <- mapvalues(results[[1]], from = c(T, F), to = c("H", "T"))
left_right <- mapvalues(results[[2]], from = c(T, F), to = c("L", "R"))
```


```{r}
print(heads_tails)
print(left_right)
```

```{r}
summary(heads_tails)
```

```{r}
dput(heads_tails, file="heads_tails.txt")
dput(left_right, file="left_right.txt")
```

