---
title: "HMM"
author: "David Barnett"
date: "January 24, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("HMM")
```

```{r}
data = read.table("C:/Users/david/OneDrive/Documents/CalPoly/Fellowship/Monitor Study/hmm_sim.txt", sep="\n")
data = c(data)[[1]]
print(data)
```


```{r}
counth = 0
counts = 0
count1 = 0
count2 = 0
for (i in 2:length(data)){
  if (data[i] == "Happy") {
    if (data[i-1] != data[i]) {
      count1 = count1 + 1
    }
    counth = counth+1
  }
  else if (data[i] == "Sad") {
    if (data[i-1] != data[i]) {
      count2 = count2 + 1
    }
    counts = counts+1
  }
  
}

```

```{r}
count1 / counth
```

```{r}
count2/counts
```


```{r}
#MLE
n = length(data) - 1
(n - count) / n
```

```{r}
#https://www.rdocumentation.org/packages/HMM/versions/1.0
```

```{r}
hmm = initHMM(c("H","T"), c("L","R"), c(0.5,0.5), matrix(c(0.9,0.1,0.6,0.4),2), matrix(c(0.8,0.2,0.7,0.3),2))
```

```{r}
new_hmm = simHMM(hmm, 500)
```

```{r}
pred = viterbi(hmm, new_hmm$observation)
```

```{r}
pred
```

